
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
sources:

  - name: imports
    description: Imports dataset
    database: chulupi
    tables:
      - name: countries_v2
        description: gtrends countries
      - name: country_codes
        description: country_codes for enrichment

  - name: source_us
    description: source_us dataset
    database: chulupi
    tables:
      - name: dummy_data_nestle
        description: Dummy data Nestle company
      - name: deal_pipeline_stages
        description: Table containing information about deals in the Accredible CRM.
        columns:
          - name: deal_id
            description: "Unique identifier assigned to each deal in a pipeline."


      - name: deals
        description: Table containing information about deals in the CRM.
        columns:
          - name: deal_id
            description: "Unique identifier assigned to each deal in a pipeline."
            tests:
                - unique
                - not_null
          - name: pipeline_id
            description: "Identifier of the pipeline."
          - name: pipeline_name
            description: "Human-readable pipeline name."
          - name: stage_name
            description: "Human-readable stage name."
          - name: amount_in_home_currency
            description: "Monetary value of a deal in USD."
          - name: created_at
            description: "Timestamp at which a deal was first created."
          - name: close_date
            description: "Timestamp at which a deal has been closed."
          - name: deal_source_type
            description: "Channel from which a deal was sourced."
        freshness:
          warn_after: {count: 1, period: day}
          error_after: {count: 99, period: day}
        loaded_at_field: created_at

